name: compile
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository
        uses: actions/checkout@v1
      - name: Toolchain
        uses: ./.github/actions/rust-toolchain
      - name: Build
        run: cargo build --all --release --target x86_64-unknown-linux-musl && strip target/release/rat && mv target/release/rat target/release/rat_amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/rat_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
