name: Compile Linux binary
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          default: true
          override: true

      - name: Build binary
        run: |
          cargo build --all --release --verbose --target x86_64-unknown-linux-gnu
          # && strip target/release/librat.so \
          # && mv target/release/librat.so target/release/rat_amd64.so

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin-amd64-linux
          path: ./target
            # target/release/rat_amd64.so
            # data/amp.ttl
            # data/manifest.ttl

      - name: Release binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/rat_amd64.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
